src/media/js/main.js

This is just because it's a nightmare to test on dev/stage. We'll test on prod.

Only check update for mozilla.com users for now (bug 1114794)

---

src/dev.html
src/media/css/compat-filtering.styl
src/media/css/detail/base.styl
src/media/css/detail/header.styl
src/media/css/detail/info.styl
src/media/css/lib/typography.styl
src/media/css/listing.styl
src/media/css/previews-tray.styl
src/media/css/site.styl
src/media/css/tiles.styl
src/media/css/typography.styl
src/media/css/view-all-tab.styl
src/media/js/views/app.js
src/templates/detail/main.html
src/templates/detail/receipt.html

https://github.com/mozilla/fireplace/pull/876
Making new PR to point to feed branch (as opposed to feed-detail branch before)

refresh app detail page pt.2, app info (bug 1103201)

---

src/media/css/feed.styl

r? @ngokevin @spasovski @mstriemer 
See also:
* https://github.com/mozilla/zamboni/pull/2823
* https://github.com/mozilla/transonic/pull/88
* https://github.com/mozilla/marketplace-operator-dashboard/pull/14

Add MTN brand color

---

src/dev.html
src/media/css/detail/base.styl
src/media/css/detail/header.styl
src/media/css/detail/info.styl
src/media/css/detail/reviews.styl
src/media/css/ratings.styl
src/media/css/site.styl
src/media/js/helpers_local.js
src/templates/_macros/rating.html
src/templates/detail/main.html
src/templates/ratings/main.html

Re-created PR from https://github.com/mozilla/fireplace/pull/880 to point to feed branch

refresh app detail page pt.3, reviews (bug 1103201)

---

src/dev.html
src/media/css/detail/base.styl
src/media/css/detail/content-ratings.styl
src/media/css/detail/more-info.styl
src/media/css/detail/reviews.styl
src/media/css/lib/mixins.styl
src/media/js/categories.js
src/media/js/compatibility_filtering.js
src/media/js/helpers_local.js
src/media/js/ratings.js
src/media/js/views/app/abuse.js
src/templates/detail/content_ratings.html
src/templates/detail/main.html
src/templates/ratings/add.html

- remove box shadow around the detail section on mobile
- fix the add/edit review and abuse modals 
- TODO: deserialize package sizes on the backend.

refresh app detail page pt.4, more info (bug 1103201)

---

src/media/css/desktop-promo.styl
src/templates/feed.html

Desktop promo subheading

---

src/media/js/mkt-carousel.js
src/templates/desktop-promo.html

Slide when clicking on partial promo item

---

src/dev.html
src/media/css/detail/reviews.styl
src/media/css/header.styl
src/media/css/lib/typography.styl
src/media/css/reviews.styl
src/media/css/typography.styl
src/media/js/helpers_local.js
src/media/js/ratings.js
src/templates/_includes/back_to_app.html
src/templates/_includes/reviews_sidebar.html
src/templates/_includes/reviews_summary.html
src/templates/_macros/review.html
src/templates/app/abuse.html
src/templates/detail/main.html
src/templates/ratings/edit.html
src/templates/ratings/main.html
src/templates/ratings/rating.html

- in the shots, there's a misalignment with the timestamp. that's been fixed.
another screenshot

refresh reviews page (bug 1118631)

---

fabfile.py

Jenkins fabfile prep

---

src/media/css/feed/brands.styl
src/media/css/feed/feed.styl
src/templates/_macros/feed_item.html
src/templates/feed/feed_brand.html

- app tiles are misaligned, @spasovski is on that
- no background curves yet

refresh ed. brand landing page (bug 1103205)

---

src/dev.html
src/media/css/app-list.styl
src/media/css/feed/brands.styl
src/media/css/feed/collections.styl
src/media/css/feed/feed.styl
src/media/css/feed/landing.styl
src/media/css/feed/layout.styl
src/media/js/helpers_local.js
src/media/js/image-deferrer-mkt.js
src/media/js/main.js
src/media/js/views/feed/feed_collection.js
src/templates/_macros/feed_item.html
src/templates/feed/feed_brand.html
src/templates/feed/feed_collection.html

PR before swapping the branch to point to feed: https://github.com/mozilla/fireplace/pull/890

refresh collection detail pages (bug 1103202/1103304)

---

bower.json
config.js
src/media/js/apps.js
src/media/js/apps_buttons.js
src/media/js/payments.js
src/media/js/settings.js
src/media/js/settings_local.js.dist
src/templates/tests.html
src/tests/apps.js
src/tests/payments.js

By switching to fxpay this also adds support for
desktop payments.

Use fxpay for Marketplace payments (bug 1113801)

---

src/media/css/feed/brands.styl
src/templates/_macros/feed_item.html

brand landing curve (bug 1103303)

---

src/media/css/category-dropdown-desktop.styl
src/templates/cat_overlay.html
src/templates/nav.html

refresh cat dropdown (bug 1103225)

---

package.json

r? @ngokevin - are the other changes between 1.3.1-1.4.2 good to bring in?

Bump marketplace-gulp to 1.4.2

---

src/media/css/app-list.styl
src/media/css/buttons-loadmore.styl
src/media/css/buttons.styl
src/media/css/categories.styl
src/media/css/detail/header.styl
src/media/css/previews-tray.styl
src/media/css/site.styl
src/media/css/tiles.styl
src/media/img/pretty/arrow-r.svg
src/media/js/app_lists.js
src/media/js/main.js
src/media/js/previews.js
src/media/js/shothandles.js
src/media/js/views/search.js
src/templates/_macros/app_tile.html
src/templates/_macros/feed_item.html
src/templates/app_list.html
src/templates/category.html
src/templates/search/main.html
src/templates/user/purchases.html

TODO: Full sized image previews on desktop detail (non-responsive change).
TODO: Lightbox restyling.
TODO: Possible tweaks to JS logic for showing the bottom blue bars (only happens when a certain shot threshold is reached)

refresh screenshot previews

---

src/media/css/newsletter.styl

fix newsletter double sign-up (bug 1115086)

---

src/media/css/footer.styl
src/templates/footer.html

add desktop support link (bug 1122150)

---

src/media/js/apps_buttons.js
src/media/js/main.js
src/templates/_includes/os_x_banner.html

Depends on https://github.com/mozilla/marketplace-core-modules/pull/17.

Mac install issues banner (bug 1124243)

---

src/media/css/header.styl

nuke border on sign-in button state (bug 1116277)

---

.travis.yml
tests/settings_travis.js

This is probably still WIP, first attempt.

Run a flue on Travis

---

src/media/css/app-list.styl
src/media/css/categories.styl
src/media/css/category-icons.styl
src/media/css/header.styl
src/media/img/pretty/cats-sprite.svg
src/templates/category.html

enclose category header icons in circle on desktop (bug 1123896)

---

src/dev.html
src/media/css/app-list-filters.styl
src/media/css/app-list.styl
src/media/css/categories.styl
src/media/css/compat-filtering.styl
src/media/css/header.styl
src/media/css/search.styl
src/media/css/site.styl
src/media/js/app_list.js
src/media/js/tracking_events.js
src/media/js/views/search.js
src/templates/_includes/app_list_filters.html
src/templates/app_list.html
src/templates/category.html
src/templates/search.html
src/templates/user/purchases.html
tests/ui/app/index.js
tests/ui/app_list.js
tests/ui/category.js
tests/ui/index.js

Handles issue of uninitialized expand toggle requiring two clicks. The toggle disappearing "while" clicking (:active state). Code cleanup around search eggies whose image assets were already removed.

expand toggle related issues (bug 1123899)

---

src/media/css/detail/header.styl

nuke app detail header height (bug 1126962)

---

bower.json
src/media/css/buttons-loadmore.styl
src/media/img/icons/refresh-icon.svg
src/media/js/main.js
src/media/js/views/homepage.js
src/templates/_includes/more_button.html
src/templates/_macros/more_button.html
src/templates/errors/pagination.html
tests/ui/index.js

- Don't replace button with spinner, just spinner the icon within the button
- Depends upon https://github.com/mozilla/marketplace-core-modules/commit/8c2f7dfcff09462d4ecf9920b3fdbcb897de8322 for builder changes to not hide btn on pagination
- Feed loadmore tests
- Remove some Persona code in main.js
- Resolve some TODOs in main.js

refresh loadmore spinner (bug 1123869)

---

src/media/css/compat-filtering.styl

address compat filter styling issue on fxos (bug 1121005)

---

src/media/css/search.styl
src/media/js/views/search.js
src/templates/search.html
tests/ui/search.js

Also fixes a minor dependency issue.

no search results cleanup (bug 1127515)

---

src/templates/_includes/app_list_filters.html

Opening a PR in case we want the wording changed.

more appropriate expand toggle title (bug 1126868)

---

src/templates/privacy.html
src/templates/terms.html

fix up terms of use pages (bug 1126810)

---

src/media/css/footer.styl
src/media/css/newsletter.styl
src/templates/footer.html
tests/ui/index.js

footer should exist on tablet widths (bug 1129031)

---

src/media/css/app-list.styl
src/media/css/search.styl
src/media/css/site.styl
src/templates/errors/404.html
src/templates/search.html
tests/ui/search.js

re-add compat dropdown to empty search (bug 1127515)

---

src/media/css/header.styl
src/templates/header.html

refresh header login buttons (bug 1129350)

---

src/media/css/feed/collections.styl
src/media/css/feed/feed.styl
src/media/css/feed/index.styl
src/templates/_macros/feed_item.html

show listing coll desc on landing pages (bug 1128511)

---

src/media/css/app-list.styl

sin against nature (bug 1129367)

---

src/templates/newsletter.html

green newsletter signup buttons (bug 1127161)

---

src/media/css/search.styl

no results font color and weight (bug 1127515)

---

src/media/css/previews-tray.styl
src/media/js/previews.js
tests/ui/app/index.js
tests/ui/app_list.js

fix missing single SS issue (bug 1128996)

---

src/media/css/app-list.styl
src/media/css/feed/index.styl
src/media/css/lib/colors.styl
src/templates/_macros/feed_item.html

address colored grid borders better (bug 1130989)

---

tests/ui/app_list.js

I was working on some test updates and these tests started failing because they had no assertions. I wasn't sure why that happened so I moved the `if`s to not register empty test cases.
Running with or without these changes yields 255 tests (I'm assuming that's assertions?). With the changes in it doesn't run the test cases that have no tests in them.
Before:
```
Starting with url: http://localhost:8675/langpacks/2.2
Starting test
PASS API call was made
Starting with url: http://localhost:8675/langpacks/2.2
```
After:
```
Starting with url: http://localhost:8675/langpacks/2.2
arting test
PASS API call was made
Starting with url: http://localhost:8675/langpacks/2.2
```

Don't register app_list tests that will be skipped

---

src/media/css/feed/feed.styl
src/media/css/lib/typography.styl
src/templates/_macros/feed_item.html

all collections have a single curve now (bug 1131539)

---

src/media/js/mobilenetwork.js
src/media/js/tracking_events.js
src/media/js/views/app.js
src/media/js/views/category.js
tests/ui/category.js
tests/ui/index.js

It was only getting tracked in mobilenetwork.js if it was a phone
@diox r?

make sure to always track region (bug 1124458)

---

src/media/css/feed/icon-grid.styl
src/templates/_macros/app_tile.html
src/templates/_macros/feed_item.html
src/templates/_macros/market_button.html
tests/ui/feed.js

only show price for feed grid app labels (bug 1128647)

---

src/media/css/header.styl

fix logo clipping on retina mobile (bug 1134402)

---

src/media/js/reviews.js

narrow edge case. have to click cancel within a few second window

don't need to trigger review modal twice (bug 1132473)

---

src/templates/app/index.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1132138#c6

Only show file size for packaged apps (bug 1132138)

---

src/media/js/settings_app.js
tests/unit/settings.js

Extend our settings with body[data-settings]

---

package.json

r? @ngokevin 
Don't merge this until after this week's tag.

Upgrade marketplace-gulp to 3.1.0.

---

README.md

[http://localhost:8675/tests](http://localhost:8675/tests) just leads me to a 404 page :<

Update the README on how to run the unit tests.

---

src/media/js/compat_filter.js
src/media/js/tracking_events.js
tests/lib/helpers.js
tests/ui/compat_filter.js
tests/ui/desktop_promo.js
tests/ui/index.js
tests/unit/compat_filter.js

- Add dimension2 to track the user's selected active platform filter. Session scope.
- Add dimension4 to to track the user's detected platform. Session scope.
- Add event when user changes platform filter preference. Send the platform as the event value.
- Change dimension 2 when user changes platform filter preference.

update UA for platform filtering (bug 1141367)

---

src/templates/_macros/market_button.html
tests/ui/installs.js
tests/ui/langpacks.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1139416

Fix install button text for langpacks (bug 1139416)

---

src/templates/_includes/os_x_banner.html

update OS X banner wording (bug 1135156)

---

src/templates/tests.html

Fixes [bug 1042858](https://bugzilla.mozilla.org/show_bug.cgi?id=1042858).

Remove unused `tests.html` template file.

---

src/media/css/footer.styl
src/templates/footer.html

Tested that it looks the same as current on tablet + desktop.

chop footer anchors into blocks (bug 1135189)

---

src/templates/app/index.html

Added link to developer's name. In line 210

Bug 1135143 - Link to developer app results from "More Information" block

---

bower.json

Just getting Travis to build this...

Always use localStorage in tests

---

src/media/css/feed/shelves.styl

adjust TEF shelf landing on desktop (bug 1145654)

---

src/media/css/feed/layout.styl
src/media/js/compat_filter.js
src/media/js/views/homepage.js
src/templates/homepage.html
tests/ui/feed.js
tests/ui/index.js

- add feed collection endpoints to device filter redlist
- rename home-feed to feed-home, homie

don't device filter collections (bug 1146856)

---

tests/serve.sh

Just going to let Travis build this.

Don't force a marketplace-constants version

---

src/media/js/desktop_promo.js

This just includes the strings for the next desktop promo update in an unused array so that they can be extracted early.

Include the strings for the next desktop promo update

---

src/media/js/elements/nav.js
tests/ui/nav.js
tests/ui/platform_selector.js
tests/unit/elements--nav.js

I've seen classList.toggle(CLASS, <undefined>) fail on Chrome, so I do a check on ```bool === undefined```.

fix background_hidden, unjquery nav, unit tests (bug 1150804)

---

src/media/js/elements/nav.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1151456

Only set min-height on main if mktNavEnabled

---

src/dev.html
src/media/css/categories.styl
src/media/css/category-icons.styl
src/media/css/elements--nav.styl
src/media/css/header--categories.styl
src/media/css/lib/mixins.styl
src/media/img/pretty/categories-sprite-alt.svg
src/media/img/pretty/categories-sprite-black.svg
src/media/img/pretty/categories-sprite.svg
src/templates/mkt_nav.html

New category icons for <mkt-nav> (bug 1148164, 1148166)

---

src/dev.html
src/media/css/app-list-filters.styl
src/media/css/elements--nav.styl
src/media/css/header--categories.styl
src/media/css/nav--settings.styl
src/media/js/main.js
src/templates/mkt_nav.html
tests/ui/nav.js
tests/ui/nav_settings.js

- Also fix some padding with the empty space left by moving the platform selector

mobile settings nav (bug 1148162)

---

src/dev.html
src/media/css/elements--header.styl
src/media/css/elements--nav.styl
src/media/css/header--search.styl
src/media/css/header--settings.styl
src/media/js/elements/header.js
src/templates/header.html
tests/ui/header.js

I plan on separating the mobile nav with the desktop header so we can better layout the desktop header. But for now, I'm just getting this out there to close bugs and move on.

settings menu for desktop (bug 1148162)

---

src/media/css/footer.styl
src/media/css/lib/mixins.styl

RTL the footer (bug 1145351)

---

src/media/css/header.styl

> Before
> After
> After desktop

Less padding on the mobile recommendations link

---

src/media/css/elements--nav.styl
src/media/js/elements/header.js

Hide the mkt-nav-root selection when searching (bug 1153210)

---

src/media/css/detail/header.styl
src/media/js/apps.js

Lowercase on app availability removed

Bug 1146149 - App availability status shouldn't use lowercase on label (because of localizations)

---

src/media/js/elements/nav.js

r? @ngokevin 
> Before
> After

Only set min-height on main at mobile widths (bug 1151456)

---

src/media/css/account.styl
src/templates/settings.html
tests/ui/settings.js

RTL account settings page (bug 1148615)

---

src/media/css/desktop-promo.styl

Support RTL for desktop promo

---

src/media/css/buttons-loadmore.styl
src/media/css/buttons.styl
src/media/css/feed/brands.styl
src/media/css/feed/collections.styl
src/media/css/feed/feed.styl
src/media/css/feed/icon-grid.styl
src/media/css/tiles.styl
src/templates/_macros/app_tile.html

RTL marketplace home (bug 1148605)

---

.travis.yml

Allow failures for uitest-phantom until we fix it

---

src/media/css/elements--categories.styl
src/media/css/elements--nav.styl
src/media/css/header.styl
src/media/css/lib/mixins.styl
src/media/css/site.styl
src/media/js/elements/nav.js

RTL nav support on the left (bug 1148600, 1148595)

---

src/media/css/elements--header.styl
src/media/css/header--search.styl
src/media/css/header.styl
src/media/css/lib/mixins.styl
src/templates/header.html

> 320px wide
> 768px wide
> 1024px wide
r? @ngokevin

RTL-ify the new search dropdown (bug 1148599)

---

bower.json
src/media/css/lib/categories.styl
src/media/css/lib/index.styl
src/media/css/lib/mixins.styl
src/media/css/lib/spinner.styl
src/media/css/notification.styl
src/media/css/pretty-select.styl
src/media/js/main.js
src/media/js/previews.js

use html[dir] over body class for rtl

---

bower.json
src/media/js/main.js

RTL Banners (bug 1148603)

---

src/media/css/elements--header.styl
src/media/css/header--search.styl

Align search on mobile (bug 1157356)

---

src/media/css/app-list-filters.styl
src/media/css/app-list.styl

Ignore the app tile icon misalignment in RTL - that gets addressed in the homepage PR.

RTL popular page (bug 1148607)

---

src/media/css/buttons-loadmore.styl
src/media/css/buttons.styl
src/media/css/detail/header.styl
src/media/css/feed/brands.styl
src/media/css/feed/collections.styl
src/media/css/feed/feed.styl
src/media/css/feed/icon-grid.styl
src/media/css/tiles.styl
src/templates/_macros/app_tile.html
src/templates/_macros/feed_item.html

Includes everything from the revert and subsequent .info related fixes.

RTL homepage with .info fixes (bug 1148605)

---

bower.json
config.js
src/media/js/mobilenetwork.js
test-main.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1151991
https://bugzilla.mozilla.org/show_bug.cgi?id=1153002
https://bugzilla.mozilla.org/show_bug.cgi?id=1154951
https://bugzilla.mozilla.org/show_bug.cgi?id=1157067

Add new regions and carriers (bug 1151991, bug 1153002, bug 1154951, bug  1157067)

---

src/media/css/previews.styl

Line up the preview tray for RTL (bug 1155376)

---

src/media/css/elements--header.styl
src/media/css/header--search.styl
src/media/js/elements/header.js

Centre search input

---

src/media/css/newsletter.styl
src/media/js/newsletter.js
src/templates/newsletter.html

Custom validation messages on newsletter form (bug 1158801)

---

src/media/js/elements/select.js

Set padding-right on platform select for RTL (bug 1160347)

---

src/templates/newsletter.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1160290
Because this will blow up when we add 250+ countries.

Remove regions dropdown from newsletter (bug 1160290)

---

src/media/css/elements--nav.styl

https://bugzilla.mozilla.org/show_bug.cgi?id=1161478

Don't allow horizontal scrolling of mobile menu (bug 1161478)

---

src/media/css/detail/more-info.styl

Columns are now aligned consistently

Bug 1143230 - Columns not aligned consistently on app detail pages

---

tests/unit/compat_filter.js

Update unit tests to reflect the changes in f38b31329ab9bc557b8e787dac8e5d1703cd53b4.
r? @ngokevin

Update unittests to reflect f38b3132

---

src/media/css/image-deferrer.styl
src/media/css/previews.styl
src/media/js/image-deferrer-mkt.js
src/media/js/previews.js
src/templates/_macros/previews.html

To test this locally point your settings_local to stage and visit `/app/test-app-bat1429/`

enable video previews on desktop app detail (bug 1066871)

---

src/media/js/routes.js

Use multi-search for categories when meowEnabled

---

src/media/css/newsletter.styl

Footer Newsletter bar is now align correctly

Bug 1162913 - Footer Newsletter bar is not align correctly

---

src/media/js/routes.js
src/media/js/views/app/abuse.js
src/media/js/views/website/issue.js
src/templates/website/index.html
src/templates/website/issue.html
tests/ui/website/issue.js

This is mobile only for now (no modal) since we don't support desktop yet.

Report website issue view (bug 1161864)

---

.travis.yml
Makefile
package.json
sherlocked.js

Testing this out. We need to run the PR in the master repo here since Travis secure environment variables required for Sauce can't be decrypted from forked PRs.
I deployed the frontend/API/nginx at http://sherlocked.dev.mozaws.net/ manually via Mozilla's AWS using EC2 for now. 
Using flue.paas for now while I wait for https://github.com/travis-ci/travis-build/pull/454

I AM SHERLOCKED (bug 1125417)

---

src/media/js/helpers_local.js

"works offline" is now start with lowercase word

Bug 1167910 - "Works offline" should be start with lowercase word

---

src/media/css/account.styl
src/templates/settings.html

changed "Account Settings" to "Settings"

Bug 1080289 - Page title of "My Account" page is "Account Settings"

---

src/media/js/views/app.js
src/media/js/views/app/abuse.js
src/media/js/views/app/privacy.js
src/media/js/views/app/ratings.js
src/media/js/views/app/ratings/add.js
src/media/js/views/newsletter_signup.js
src/media/js/views/search.js
src/media/js/views/terms.js
src/media/js/views/website.js
src/media/js/views/website/issue.js

This adds the strings that will be used for the upcoming header changes so they can be translated. I'll probably hold off on landing the header changes until after the tag so we've got more time to translate these.

Land strings for the upcoming header changes (bug 1168485)

---

locale/ru/LC_MESSAGES/messages.po

Some translations confused me, so I did my best to fix it

Fix Russian grammar

---

src/media/css/elements--categories.styl

Fixed this Css issue of Category links as suggested

Bug # 1160364 rounded category icon strokes (+)

---

src/media/css/header.styl
src/media/css/lib/hambacker.styl
src/media/css/lib/layout.styl

This just makes the hambacker more portable so it can be used in the categories menu.

Make the hambacker more portable

---

src/media/js/views/search.js
tests/lib/helpers.js
tests/ui/search.js

> Before&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;After

Treat search?author=whoever as a leaf page (bug 1170224)

---

src/media/css/newsletter.styl

Centre the newsletter form as a block (bug 1169215)

---

src/media/js/routes.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1164489

Use fireplace variant of multi-search API (bug 1164489)

---

locale/ar/LC_MESSAGES/messages.po
sherlocked.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1169231

[WIP] RTL preview missing indicator

---

src/media/css/elements--categories.styl
src/media/js/elements/categories.js
src/media/js/elements/header.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1166413

Highlight active category, use borders on mobile too (bug 1166413)

---

src/media/js/compat_filter.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1170018

Make gettext lazy for the compat_filter module (bug 1170018)

---

package/iframe/main.js
package/iframe/manifest.webapp
src/media/js/apps.js
src/media/js/webactivities.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1172510

Add web activity for OpenMobile ACL (bug 1172510)

---

src/media/css/detail/base.styl
src/media/css/detail/reviews.styl
src/media/css/reviews.styl
src/media/css/typography.styl
src/templates/_includes/reviews_summary.html

some RTL review inconsistencies (bug 1171422)

---

src/media/js/views/debug.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1171108

Add back country name in debug page region change notification (bug 1171108)

---

src/media/css/detail/base.styl

Bug 1174347 - Categories are not in bold in details page for Websites

---

src/media/css/detail/base.styl
src/templates/website/index.html

BUG : 1174351 button set to link and font weight set to 500

BUG : 1174351 report issue button to link

---

src/media/js/settings_local_hosted.js

Meow all the devs

---

src/media/css/app-list-filters.styl

https://bugzilla.mozilla.org/show_bug.cgi?id=1176685

Only show border on new/popular on mobile (bug 1176685)

---

bower.json
src/media/js/content_filter.js
src/templates/_includes/app_list_filters.html
tests/unit/content_filter.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1173023

Hide content filtering on "desktop"

---

src/media/css/search.styl
src/templates/app_list.html
src/templates/category.html
src/templates/search.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1176122
https://bugzilla.mozilla.org/show_bug.cgi?id=1176113

Content filter no results 1176122

---

src/media/css/app-list-filters.styl
src/media/css/header.styl
src/media/js/elements/header.js

Some issues still remain but I'll file separate bugs for those. Not sure how much time we should spend on these since Edge seems like it will cover all the older flexbox/event issues etc.

ie10 issue roundup part one (bug 1135213)

---

src/templates/_macros/market_button.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1179801
This will need to change when we add support for desktop but this should work for now.

Use mobile_url for websites if available (bug 1179801)

---

src/media/css/content-filter.styl
src/media/css/elements--select.styl

https://bugzilla.mozilla.org/show_bug.cgi?id=1177692

Fix RTL layout of content select dropdown (bug 1177692)

---

src/media/css/elements--nav.styl

back button correctly aligned in RTL (bug 1179168)

---

locale/ar/LC_MESSAGES/messages.po

https://bugzilla.mozilla.org/show_bug.cgi?id=1177677

Fix </b> tag in Arabic translation (bug 1177677)

---

src/media/css/header.styl
src/media/js/elements/header.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1180150

Ellipsise the hub-and-spoke header title (bug 1180150)

---

src/media/css/detail/post-install-message.styl

https://bugzilla.mozilla.org/show_bug.cgi?id=1179795

Align post install message correctly RTL (bug 1179795)

---

src/media/css/detail/website.styl
src/templates/website/index.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1175675

Add horizontal separator to website detail under button (bug 1175675)

---

README.md

Corrected link to Packaged Apps Documentation

---

package/iframe/main.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1180909

Remove workaround for old *feature bug and test hasFeature before using it (bug 1180909)

---

src/templates/_macros/feed_item.html

goes with https://github.com/mozilla/zamboni/pull/3107

don't html-escape collection names (bug 1142301)

---

src/media/js/tracking_events.js

track websites using name:id (bug 1179463)

---

src/media/js/views/app/ratings.js
src/media/js/views/app/ratings/add.js
src/media/js/views/app/ratings/edit.js
src/media/js/views/app/ratings/rating.js
src/media/js/views/app/receipt.js
src/media/js/views/category.js
src/media/js/views/feed_landing.js

Same sort of thing as https://github.com/mozilla/fireplace/commit/ec52e30bb4ad66264a91f8c386490429d7776ee7

Handle non-BMP slugs (bug 1068649)

---

src/media/js/buttons.js
tests/unit/buttons.js
tests/unit/helpers.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1180839

Simplify the l10n string for free install text (bug 1180839)

---

src/media/js/update_banner.js
tests/ui/update_banner.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1172909

Only show one update banner (bug 1172909)

---

bower.json
src/media/js/compat_filter.js
src/media/js/content_filter.js
tests/unit/content_filter.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1182227
r? @ngokevin

Lazily translate content filter strings (bug 1182227)

---

src/media/js/buttons.js
test-main.js
tests/unit/buttons.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1183072

Use "Install" button text for purchased apps (bug 1183072)

---

src/media/js/buttons.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1183072

Set app install state before updating text (bug 1183072)

---

src/media/js/webactivities.js

update OM chipset string, fix parsing

---

src/media/js/webactivities.js

file modified:   src/media/js/webactivities.js
Use of "capabilities.iframed" instead of "window.self !== window.top"

Consolidate checks for the iframe package (bug 1117771)

---

src/dev.html
src/media/css/feed/websites.styl
src/media/js/feed.js
src/media/js/feed_websites.js
src/media/js/helpers_local.js
src/media/js/init.js
src/media/js/settings_local.js.dist
src/templates/_macros/feed_websites.html
src/templates/homepage.html

r? @ngokevin  @spasovski 
Video here: http://www.chuck.mn/0s2y1Y2e3U1v
It currently hooks up to the multisearch for sites as a separate defer block completely, which is not the final solution—we'll be adding the websites to the feed endpoint. I won't merge until I get this behind a setting.

[wip] Adds featured websites to top of feed (bug 1190545).

---

bower.json
package.json
tests/unit/content_filter.js
tests/unit/helpers.js

pull in l10n optimizations (bug 1144425)

---

src/media/js/webactivities.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1192076
https://bugzilla.mozilla.org/show_bug.cgi?id=1192083

Navigate to the ACL app when installing it and launch it after install (bug 1192076, bug 1192083)

---

src/media/css/header.styl

Bug 1190407 - [Back to App link] unnecessary padding 

---

src/media/css/feed/websites.styl
src/media/js/settings_app.js
src/templates/_macros/feed_websites.html
src/templates/homepage.html

Will sit on this until I can verify against the API changes that are currently being pushed to dev.

Enable MeOWs on the homepage by default (bug 1190545)

---

src/media/js/buttons.js
src/templates/_macros/feed_websites.html

r? @ngokevin 
Using `<a target="_blank">` doesn't work for some reason, gotta force it through with `window.open`.

Use JS to open websites in a new window (bug 1192991).

---

package.json

Bump marketplace-gulp version to get rid of the spammy autoprefixer deprecation notice.

---

src/media/js/tracking_events.js
src/templates/_macros/feed_websites.html

Adds event tracking for non-button clicks to homepage websites.

---

src/media/css/footer.styl
src/templates/footer.html

Footer-text visible color(Bug:1190107)

---

src/media/css/footer.styl
src/templates/footer.html

Reverts mozilla/fireplace#1430

Revert "Footer-text visible color(Bug:1190107)"

---

src/media/js/apps.js
src/templates/_macros/app_tile.html

don't show desktop games on mobile (bug 1195841)

---

src/media/css/games/listing.styl
src/media/css/site.styl
src/templates/games/index.html
src/templates/games/listing.html

add pagination to game listing page

---

src/media/js/apps.js

Disable featured game websites on desktop, but not all MOWs (bug 1196359).

---

src/templates/feedback.html

Making title structure in sync with other pages

[Bug 1193282] No left-margin - re

---

src/media/css/games/games.styl
src/media/css/games/home.styl

https://marketplaceux.etherpad.mozilla.org/16

address UX stuff for games

---

package/iframe/js/features.js
package/iframe/js/main.js
package/iframe/tests/features.test.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1172487
I need to run more tests to make sure it doesn't cause any regressions, but it should be almost ready.

Use new buchets style when generating feature profile (bug 1172487)

---

src/templates/app/abuse.html

Probably r- due to typo in commit message.

report app abuse form UI debt (bug 1189756)

---

src/media/css/detail/reviews.styl

Before:
http://imgur.com/mj7ClIr,V9XZlLw
After:

Fix padding between review stars and review count (bug #1198905).

---

src/media/js/routes.js
src/media/js/settings_app.js
src/media/js/settings_local.js.dist
src/media/js/settings_local_hosted.js
src/media/js/views/addon.js
src/media/js/views/app.js
src/media/js/views/debug.js
src/templates/addon/index.html

initial add-on detail page

---

src/media/css/detail/header.styl

display issues in websites details page (bug 1199620)

---

src/media/js/webactivities.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1194464

Fix openmobile ACL activity spinner (bug 1194464)

---

src/templates/addon/index.html

Waiting on version fixes to test.

[wip] Adds description to addon detail page.

---

src/media/js/helpers_local.js
src/templates/addon/index.html

List addon filesize on detail page.

---

.travis.yml
Makefile

Use a different marketplace-gulp version

---

package.json
src/media/js/addon.js
src/media/js/feed_websites.js
src/media/js/previews-buttons.js

This includes the changes from https://github.com/mozilla/marketplace-gulp/pull/24.

Fail the build when lint fails

---

src/media/js/views/addons.js
src/templates/addon/list.html

UI for addons list

---

src/media/js/helpers_local.js
tests/unit/template.js

Use Math.pow instead of bitwise XOR when trying to do exponents.

---

src/media/js/views/addons.js
src/templates/addon/list.html

Reverts mozilla/fireplace#1502

Revert "UI for addons list"

---

src/templates/_includes/personalization.html

Remove all personalization subnav except for addons.

---

src/dev.html
src/media/css/addon-tiles.styl
src/media/css/buttons.styl
src/media/css/detail/base.styl
src/media/css/tiles.styl
src/media/js/apps.js
src/media/js/buttons.js
src/media/js/views/addon.js
src/media/js/views/langpacks.js
src/templates/_macros/addon_tile.html
src/templates/_macros/app_tile.html
src/templates/_macros/detail.html
src/templates/_macros/market_button.html
src/templates/addon/index.html
src/templates/app/index.html
src/templates/website/index.html

I gave up on trying to make the existing install logic play nice with extensions. It might be a good idea to add this to the existing 'addon.js' instead but feel free to comment.

addon details page

---

src/media/css/addon-tiles.styl
src/templates/_macros/addon_tile.html
src/templates/addon/list.html

The existing tiles on mobile will need some tweaking for zebra-striping and updated padding. That will be another PR and this page is neatly independent for now.

addon listing page

---

src/templates/footer.html

Show link to content tools in footer if the user has permission to log in to them.

---

package/iframe/js/features.js
package/iframe/js/main.js
src/media/js/settings_local_hosted.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1214817
Needs a new package, and a recent FxOS build so that hasFeature('web-extensions') works.

Enable FxOS Add-ons if using a compatible FxOS device (bug 1214817)

---

src/media/js/webactivities.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1212918

Handle 'marketplace-category' w/ {slug: 'addons'} Web Activity (bug 1212918)

---

src/media/css/addon-list.styl
src/media/css/addon-tiles.styl
src/media/css/header--global.styl
src/media/css/nav--global.styl
src/media/js/views/category.js
src/templates/_macros/addon_tile.html
src/templates/addon/index.html
src/templates/categories.html
src/templates/header.html

I'll keep a running set of commits and before/after screenshots here for reference.

nav polish

---

package/iframe/js/features.js
package/iframe/js/main.js
package/iframe/tests/features.test.js
src/media/js/carrier.js
src/media/js/settings_local.js.dist
src/media/js/settings_local_hosted.js
src/templates/nav.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1219285

Detect late-customization and homescreens support (bug 1219285)

---

package/iframe/js/features.js
package/iframe/tests/features.test.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1195704

Detect UDPSocket feature flag (bug 1195704)

---

src/media/css/nav--global.styl
src/templates/category.html

fix duplicate categories menu issue (bug 1218809)(1515)

---

package/iframe/manifest.webapp
src/media/js/webactivities.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1219811

Add activities to open an addon or a website detail page (bug 1219811)

---

src/media/css/nav--global.styl

add settings button width for chrome (bug 1219002)(1515)

---

src/media/css/header--global.styl
src/media/css/header--search.styl
src/media/js/nav.js
src/templates/header.html

r? @ngokevin 
- Mobile: http://chuck.mn/2E1M1H002o2f
- Desktop: http://chuck.mn/2u2K0m0a0141

Do not clear seach input placeholder text on blur (bug 1219513).

---

src/media/css/nav--global.styl

more specific new/popular menu states (bug 1220192)(1515)

---

src/templates/privacy.html
src/templates/terms.html

See https://github.com/mozilla/zamboni/pull/3422

NOW updated ToS for 2.5 launch. (bug 1217680)

---

src/media/js/header_footer.js

This won't change anything for the desktop header since it's absolutely positioned. To test this locally try http://pastebin.com/HC0Y5XGA

always insert banners before header (1515)

---

src/media/css/header--global.styl
src/media/js/views/addon.js
src/media/js/views/app.js
src/media/js/views/app/abuse.js
src/media/js/views/app/ratings.js
src/media/js/views/app/ratings/add.js
src/media/js/views/app/ratings/edit.js
src/media/js/views/app/ratings/rating.js
src/media/js/views/website.js

add spoke-header page type (bug 1218945)(1515)

---

src/templates/search.html

expand previews on desktop search (bug 1218831)(1515)

---

src/media/css/header--global.styl
src/media/js/views/recommended.js

make recommended page spoke-header (bug 1219881)(1515)

---

src/media/css/categories.styl
src/media/css/header--global.styl
src/media/css/sort-toggle.styl
src/media/js/routes.js
src/media/js/views/category_websites.js
src/media/js/views/popular_websites.js
src/templates/categories.html
src/templates/category.html

add site categories (bug 1219782)(1515)

---

src/media/css/sort-toggle.styl
src/media/js/views/category.js
src/media/js/views/category_websites.js
src/media/js/views/new_websites.js
src/templates/_includes/personalization.html
src/templates/category.html

Our subheaders need to be refactored at some point since too many edge cases exist.

clean up categories subheader (bug 1221229)

---

src/media/css/header.styl

fix recommendations toggle selector

---

src/media/css/nav--global.styl
src/media/js/nav.js
src/templates/categories.html
src/templates/nav.html

Reverts mozilla/fireplace#1553

Revert e7dbd12eb6b59f692875ba3fe580a8ce25244240

---

src/templates/privacy.html
src/templates/terms.html

Goes with https://github.com/mozilla/zamboni/pull/3431

Added localizations for updated dev agreement (2.5).

---

src/media/js/views/feedback.js
src/templates/feedback.html

make feedback page spoke-header

---

src/templates/settings.html

Bug 1189337 - Remove footer + Sign Out button on settings page

---

src/media/js/helpers_local.js
src/templates/_macros/addon_tile.html
src/templates/category.html
src/templates/product_list.html
src/templates/search.html

CAUTION: Was done in 5 minutes and may literally break everything. Test liberally as I will continue to.

replace appOrWebsite to fix multi-search results

---

src/media/css/addon-tiles.styl
src/templates/_macros/addon_tile.html
src/templates/_macros/app_tile.html
src/templates/_macros/deferred_icon.html

addon tile icons on should be on the right side

---

src/media/js/views/recommended.js
tests/lib/app_list.js
tests/ui/app_list.js
tests/ui/search.js

Far, far from ideal, but it's a start. The tests using app_list should probably be rewritten to be more clear, they are difficult to read, partly because of the switch to multi-search almost everywhere. Once this is done and tests finally pass we can start adding more covering non-apps...

Fix search and app_list ui tests

---

src/templates/settings.html

updated the ```Get Involved``` link with new one

updated the "Get involved" link

---

src/templates/_macros/detail.html
src/templates/ratings/add.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1228777 
@spasovski bug may needs to triage, if that pass, then **r?**

Fix hub/spoke header for submit reviews & error pages (bug 1228777)

---

src/media/css/header--global.styl
src/media/js/views/search.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1227202

Fix hub/spoke header title on author's app list (bug 1227202)

---

src/media/css/reviews.styl
src/templates/_macros/review.html

alignment of 'date' and 'report'

Bug : 1185832

---

src/media/js/views/search.js

works locally yet preserves the previous work done by the contributor for 1.1

fix debug page after 1.1 fix (bug 1228384)

---

src/media/css/header--global.styl
src/media/js/views/new_apps.js
src/media/js/views/popular_apps.js

Another regression shows up for #1583 on categories page & My Apps page

Fixed nav toggle header 

---

src/media/css/detail/info.styl
src/templates/app/index.html

API part was removed in https://github.com/mozilla/zamboni/commit/fc23c3c9325448b5cf49ab96045da46b67f58b60 I forgot to update fireplace as well.

Remove the feature to add a banner message (bug 1164222)

---

src/media/js/apps.js
tests/lib/app_list.js
tests/ui/app_list.js
tests/ui/category.js
tests/ui/index.js
tests/ui/installs.js
tests/ui/nav.js
tests/ui/platform_selector.js
tests/ui/previews.js
tests/ui/search.js
tests/ui/settings.js

Not super happy with the removal of the API call asserts. Other weirdness happens with requirejs erroring out locally yet not consistently on feed and shelf pages.

more tests fixed, requirejs errors happen locally

---

src/media/css/reviews.styl

Bug 1234202 - HTML Warning message is not correctly displayed in submit form

---

src/templates/app/privacy.html
src/templates/ratings/edit.html

Fix hub/spoke header for Edit Review & App's privacy policy

---

src/media/css/header.styl
src/media/css/newsletter.styl
src/media/js/newsletter.js
src/templates/newsletter.html

Tried filling out the form too, worked fine.

newsletter UI debt (bug 1189753)

---

src/templates/feedback.html
src/templates/ratings/add.html

- removed "get help" links
- removed char counter
- moved star rating label to above the star input

modal prompt forms UI debt (bug 1189388)

---

src/media/css/nav--global.styl
src/media/js/views/feedback.js
src/media/js/views/newsletter_signup.js
src/media/js/views/purchases.js
src/templates/nav.html

This adds a new nav group with support links to the mobile more menu. I hope the bug behind this gets WONTFIXd since the links point to pages that only look good on desktop.
In case we wish to proceed this PR can stay up/get merged.

update more menu nav groups (bug 1189377)

---

bower.json
src/media/css/notification.styl
src/media/js/buttons.js
src/media/js/newsletter.js
src/media/js/payments.js
src/media/js/views/addon/abuse.js
src/media/js/views/app/abuse.js
src/media/js/views/app/receipt.js
src/media/js/views/feedback.js
src/media/js/views/settings.js
src/media/js/views/website/issue.js

negative state notifications for UI debt (bug 1189762)

---

src/media/js/content-ratings.js
src/templates/_includes/content_ratings.html

"IARC no longer uses icons for those"

Remove icons for IARC descriptors/interactives

---

src/media/js/main.js
src/templates/_includes/os_x_banner.html
src/templates/incompatible.html
src/templates/march_banner.html

show march 29 banner as the only banner (bug 1247411)

---

src/media/js/main.js
src/templates/fxos_only_banner.html
src/templates/march_banner.html

Probably r- due to typo in commit message :disappointed: 
This PR simply replaces the March banner with a more permanent message. Hopefully we're happy with the text and placement.

add permanent device compat banner (bug 1251438)

---

src/media/js/nav.js

Originally done by a contributor with some JS cleanup. I can't test this locally - we'd ideally need someone with a 1.1 device.

firefoxOS 1.1 compatibility shim (bug 1253168)

---

src/media/css/header--global.styl
src/media/js/views/homepage.js

The PR #1590 seems very old & does have conflicts. So, I have created this new pr. 
Please have a check @ddurst

Fix header title for homepage
